"use client";

import { Activity, BookOpen, CalendarDays, Clock3, Database, RefreshCw, ShieldCheck, TrendingUp, X } from "lucide-react";
import { useMemo, useState } from "react";
import { EmptyState } from "./empty-state";
import { Metric } from "./metric";
import { StatusBadge } from "./status-badge";
import { useJournalData, useManagementHistory } from "@/hooks/use-options-data";
import { label, money, number, percent } from "@/lib/format";
import type { JournalMetrics, JournalTrade, TradeManagementSnapshot } from "@/lib/types";

type Filters={lane:string;symbol:string;result:string;dateFrom:string;dateTo:string};
const initialFilters:Filters={lane:"ALL",symbol:"ALL",result:"ALL",dateFrom:"",dateTo:""};

function duration(seconds?:number|null){if(seconds==null)return "Unavailable";const minutes=Math.round(seconds/60);return minutes<60?`${minutes}m`:`${Math.floor(minutes/60)}h ${minutes%60}m`;}
function fullTimestamp(value?:string|null){return value?new Intl.DateTimeFormat("en-US",{timeZone:"America/New_York",month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit",second:"2-digit",timeZoneName:"short"}).format(new Date(value)):"Unavailable";}
function pnlClass(value?:number|null){return value==null?"text-slate-500":value>=0?"text-emerald-300":"text-rose-300";}

function SummarySkeleton(){return <div className="grid grid-cols-2 gap-4 p-5 sm:grid-cols-4 xl:grid-cols-7">{Array.from({length:7},(_,i)=><div key={i} className="skeleton h-12"/>)}</div>}
function HistorySkeleton(){return <div className="space-y-2 p-4">{Array.from({length:5},(_,i)=><div key={i} className="skeleton h-14"/>)}</div>}
function ErrorState({label:section,retry}:{label:string;retry:()=>void}){return <div className="surface p-8 text-center"><p className="text-sm font-semibold text-rose-200">{section} is unavailable</p><p className="mt-2 text-xs text-slate-500">The rest of OptionBeacon remains isolated. Retry this read-only request.</p><button onClick={retry} className="mt-4 rounded-lg border border-slate-700 px-3 py-2 text-[10px] font-bold uppercase tracking-wider text-slate-300">Retry</button></div>}

function PerformanceSummary({metrics}:{metrics:JournalMetrics}){return <div className="grid grid-cols-2 gap-x-4 gap-y-6 p-5 sm:grid-cols-4 xl:grid-cols-7"><Metric label="Total trades" value={number(metrics.total_trades,0)}/><Metric label="Win rate" value={percent(metrics.win_rate)}/><Metric label="Realized P&L" value={money(metrics.realized_pnl)} accent={pnlClass(metrics.realized_pnl)}/><Metric label="Avg win" value={money(metrics.average_winner)} accent="text-emerald-300"/><Metric label="Avg loss" value={money(metrics.average_loser)} accent="text-rose-300"/><Metric label="Profit factor" value={number(metrics.profit_factor,2)}/><Metric label="Avg hold" value={duration(metrics.average_hold_seconds)}/></div>}

function FiltersBar({filters,setFilters}:{filters:Filters;setFilters:(filters:Filters)=>void}){
  const update=(key:keyof Filters,value:string)=>setFilters({...filters,[key]:value});
  const selectClass="min-w-0 rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-xs font-semibold text-slate-200";
  return <section className="surface mt-5 p-4" aria-label="Journal filters"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-[1fr_1fr_1fr_1.2fr_1.2fr_auto]">
    <label className="grid gap-1.5"><span className="metric-label">Lane</span><select aria-label="Lane" value={filters.lane} onChange={e=>update("lane",e.target.value)} className={selectClass}><option>ALL</option><option>OB</option><option>BROAD</option></select></label>
    <label className="grid gap-1.5"><span className="metric-label">Symbol</span><select aria-label="Symbol" value={filters.symbol} onChange={e=>update("symbol",e.target.value)} className={selectClass}><option>ALL</option><option>SPY</option><option>QQQ</option></select></label>
    <label className="grid gap-1.5"><span className="metric-label">Result</span><select aria-label="Result" value={filters.result} onChange={e=>update("result",e.target.value)} className={selectClass}><option>ALL</option><option>WIN</option><option>LOSS</option><option>BREAKEVEN</option><option>UNAVAILABLE</option></select></label>
    <label className="grid gap-1.5"><span className="metric-label">From</span><input aria-label="Date from" type="date" value={filters.dateFrom} onChange={e=>update("dateFrom",e.target.value)} className={selectClass}/></label>
    <label className="grid gap-1.5"><span className="metric-label">To</span><input aria-label="Date to" type="date" value={filters.dateTo} onChange={e=>update("dateTo",e.target.value)} className={selectClass}/></label>
    <button onClick={()=>setFilters(initialFilters)} className="self-end rounded-lg border border-slate-700 px-3 py-2 text-[10px] font-bold uppercase tracking-wider text-slate-400 hover:text-slate-200">Clear</button>
  </div></section>;
}

function LanePerformance({lanes}:{lanes:(JournalMetrics&{lane:"OB"|"BROAD"})[]}){return <section className="mt-5 grid gap-4 md:grid-cols-2" aria-label="Lane performance">{lanes.map(lane=><article key={lane.lane} className="surface overflow-hidden"><header className="flex items-center justify-between border-b border-slate-800 px-5 py-4"><div><p className="eyebrow">{lane.lane==="OB"?"Authoritative lane":"Paper participation lane"}</p><h2 className="mt-1 text-base font-semibold">{lane.lane}</h2></div><StatusBadge value={lane.lane==="OB"?"AUTHORITATIVE":"PAPER"}/></header><div className="grid grid-cols-3 gap-4 p-5"><Metric label="Trades" value={number(lane.total_trades,0)}/><Metric label="Win rate" value={percent(lane.win_rate)}/><Metric label="P&L" value={money(lane.realized_pnl)} accent={pnlClass(lane.realized_pnl)}/><Metric label="Avg return" value={percent(lane.average_return_pct)}/><Metric label="Profit factor" value={number(lane.profit_factor,2)}/><Metric label="Avg hold" value={duration(lane.average_hold_seconds)}/></div></article>)}</section>}

function ResultBadge({trade}:{trade:JournalTrade}){return <StatusBadge value={trade.result}/>}

function DesktopHistory({trades,select}:{trades:JournalTrade[];select:(trade:JournalTrade)=>void}){return <div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[1060px] border-collapse text-left"><thead><tr className="border-b border-slate-800 text-[9px] font-bold uppercase tracking-[.13em] text-slate-600">{["Closed","Trade","Lane","Qty","Entry → Exit","P&L","Return","Result","Exit reason","Hold"].map(value=><th key={value} className="px-4 py-3">{value}</th>)}</tr></thead><tbody>{trades.map(trade=><tr key={trade.trade_id} onClick={()=>select(trade)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();select(trade)}}} tabIndex={0} className="cursor-pointer border-b border-slate-800/70 text-xs hover:bg-violet-400/[.035] focus:bg-violet-400/[.035]"><td className="whitespace-nowrap px-4 py-3 text-slate-500">{fullTimestamp(trade.exit_timestamp)}</td><td className="px-4 py-3"><p className="font-bold text-slate-100">{trade.symbol||"Unknown"} · {trade.direction?label(trade.direction):"Unavailable"}</p><p className="mt-1 font-mono text-[10px] text-slate-500">{trade.contract_symbol||"Contract unavailable"}</p></td><td className="px-4 py-3"><StatusBadge value={trade.lane}/></td><td className="px-4 py-3 tabular-nums text-slate-300">{number(trade.quantity,0)}</td><td className="whitespace-nowrap px-4 py-3 font-mono text-slate-300">{money(trade.option_entry_premium)} → {money(trade.option_exit_premium)}</td><td className={`whitespace-nowrap px-4 py-3 font-mono font-bold ${pnlClass(trade.realized_pnl)}`}>{money(trade.realized_pnl)}</td><td className={`px-4 py-3 font-mono ${pnlClass(trade.realized_return_pct)}`}>{percent(trade.realized_return_pct)}</td><td className="px-4 py-3"><ResultBadge trade={trade}/></td><td className="max-w-36 truncate px-4 py-3 text-slate-400">{trade.exit_reason?label(trade.exit_reason):"Unavailable"}</td><td className="px-4 py-3 text-slate-400">{duration(trade.hold_duration_seconds)}</td></tr>)}</tbody></table></div>}

function MobileHistory({trades,select}:{trades:JournalTrade[];select:(trade:JournalTrade)=>void}){return <div className="divide-y divide-slate-800 md:hidden">{trades.map(trade=><button key={trade.trade_id} onClick={()=>select(trade)} className="block w-full p-4 text-left"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-sm font-bold text-slate-100">{trade.symbol||"Unknown"} <span className="font-normal text-slate-500">{trade.direction?label(trade.direction):""}</span></p><p className="mt-1 truncate font-mono text-[10px] text-slate-500">{trade.contract_symbol||"Contract unavailable"}</p></div><p className={`shrink-0 font-mono text-sm font-bold ${pnlClass(trade.realized_pnl)}`}>{money(trade.realized_pnl)}</p></div><div className="mt-3 flex flex-wrap items-center gap-2"><StatusBadge value={trade.lane}/><ResultBadge trade={trade}/><span className="text-[10px] text-slate-600">{trade.exit_timestamp?fullTimestamp(trade.exit_timestamp):"Exit time unavailable"}</span><span className="ml-auto text-[10px] text-slate-500">{percent(trade.realized_return_pct)} · {duration(trade.hold_duration_seconds)}</span></div></button>)}</div>}

function DetailMetric({title,value,accent}:{title:string;value:string;accent?:string}){return <div><p className="metric-label">{title}</p><p className={`mt-1 text-xs font-semibold ${accent||"text-slate-200"}`}>{value}</p></div>}

function SnapshotEvent({snapshot}:{snapshot:TradeManagementSnapshot}){const title=snapshot.exit_label||snapshot.stop_management_state||snapshot.trade_coach_state||"MANAGEMENT";return <li className="relative pl-7"><span className="absolute left-0 top-1.5 size-2 rounded-full bg-violet-400 ring-4 ring-violet-400/10"/><p className="font-mono text-[10px] text-slate-500">{fullTimestamp(snapshot.captured_at)}</p><div className="mt-1 flex flex-wrap items-center gap-2"><p className="text-xs font-bold text-violet-200">{label(title)}</p>{snapshot.exit_score!=null&&<span className="text-[10px] text-slate-400">Exit Score {snapshot.exit_score}</span>}{snapshot.stale&&<StatusBadge value="STALE"/>}</div><div className="mt-1 flex flex-wrap gap-x-3 gap-y-1 text-[10px] text-slate-500">{snapshot.thesis_state&&<span>Thesis {label(snapshot.thesis_state)}</span>}{snapshot.momentum_state&&<span>Momentum {label(snapshot.momentum_state)}</span>}{snapshot.current_stop!=null&&<span>Stop {money(snapshot.current_stop)}</span>}{snapshot.management_reason&&<span>{label(snapshot.management_reason)}</span>}</div></li>}

function Timeline({trade}:{trade:JournalTrade}){const history=useManagementHistory(trade.management_history_available?trade.trade_id:undefined,trade.lane);return <section className="mt-6"><div className="flex items-center justify-between"><div><p className="eyebrow">Canonical history</p><h3 className="mt-1 text-sm font-semibold">Management timeline</h3></div>{trade.management_history_available&&<span className="text-[10px] text-slate-500">{trade.management_snapshot_count} snapshots</span>}</div>{!trade.management_history_available?<div className="mt-3 rounded-lg border border-amber-300/15 bg-amber-300/[.035] p-4 text-xs leading-5 text-amber-100/70">Canonical management history is unavailable for this trade.</div>:history.error?<div className="mt-3 rounded-lg border border-rose-400/20 p-4 text-xs text-rose-200">Management timeline could not be loaded. <button onClick={()=>history.mutate()} className="underline">Retry</button></div>:!history.data?<div className="mt-3 space-y-2"><div className="skeleton h-12"/><div className="skeleton h-12"/></div>:<ol className="mt-5 space-y-5 border-l border-slate-800 pl-4"><li className="relative pl-7"><span className="absolute left-0 top-1.5 size-2 rounded-full bg-emerald-400 ring-4 ring-emerald-400/10"/><p className="font-mono text-[10px] text-slate-500">{fullTimestamp(trade.entry_timestamp)}</p><p className="mt-1 text-xs font-bold text-emerald-200">ENTRY</p><p className="mt-1 text-[10px] text-slate-500">{trade.contract_symbol||"Contract unavailable"}{trade.option_entry_premium!=null?` @ ${money(trade.option_entry_premium)}`:""}</p></li>{history.data.map(snapshot=><SnapshotEvent key={snapshot.snapshot_id} snapshot={snapshot}/>)}{trade.exit_timestamp&&<li className="relative pl-7"><span className="absolute left-0 top-1.5 size-2 rounded-full bg-rose-400 ring-4 ring-rose-400/10"/><p className="font-mono text-[10px] text-slate-500">{fullTimestamp(trade.exit_timestamp)}</p><p className="mt-1 text-xs font-bold text-rose-200">EXIT</p><p className="mt-1 text-[10px] text-slate-500">{trade.exit_reason?label(trade.exit_reason):"Exit reason unavailable"}</p></li>}</ol>}</section>}

function TradeDetail({trade,close}:{trade:JournalTrade;close:()=>void}){return <div className="fixed inset-0 z-50 bg-black/75 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label="Trade detail"><button aria-label="Close trade detail backdrop" className="absolute inset-0" onClick={close}/><aside className="absolute inset-y-0 right-0 w-full max-w-2xl overflow-y-auto border-l border-slate-800 bg-[#090e18] p-5 shadow-2xl sm:p-7"><header className="flex items-start justify-between gap-4"><div><p className="eyebrow text-violet-300">{trade.lane} / {trade.data_quality}</p><h2 className="mt-2 text-xl font-semibold">{trade.symbol||"Unknown"} {trade.direction?label(trade.direction):"trade"}</h2><p className="mt-1 break-all font-mono text-[10px] text-slate-500">{trade.contract_symbol||"Contract identity unavailable"}</p></div><button aria-label="Close trade detail" onClick={close} className="rounded-lg border border-slate-700 p-2 text-slate-400"><X size={17}/></button></header><div className="mt-5 flex flex-wrap gap-2"><StatusBadge value={trade.lane}/><ResultBadge trade={trade}/><StatusBadge value={trade.status}/></div>
  <section className="mt-6 grid grid-cols-2 gap-5 rounded-xl border border-slate-800 bg-slate-950/35 p-5 sm:grid-cols-4"><DetailMetric title="Realized P&L" value={money(trade.realized_pnl)} accent={pnlClass(trade.realized_pnl)}/><DetailMetric title="Return" value={percent(trade.realized_return_pct)} accent={pnlClass(trade.realized_return_pct)}/><DetailMetric title="R multiple" value={trade.r_multiple==null?"Unavailable":`${number(trade.r_multiple,2)}R`}/><DetailMetric title="Hold" value={duration(trade.hold_duration_seconds)}/></section>
  <section className="mt-6"><p className="eyebrow">Entry / exit</p><div className="mt-3 grid grid-cols-2 gap-5 sm:grid-cols-4"><DetailMetric title="Entered" value={fullTimestamp(trade.entry_timestamp)}/><DetailMetric title="Exited" value={fullTimestamp(trade.exit_timestamp)}/><DetailMetric title="Option entry" value={money(trade.option_entry_premium)}/><DetailMetric title="Option exit" value={money(trade.option_exit_premium)}/><DetailMetric title="Underlying entry" value={money(trade.underlying_entry)}/><DetailMetric title="Underlying exit" value={money(trade.underlying_exit)}/><DetailMetric title="Quantity" value={number(trade.quantity,0)}/><DetailMetric title="Exit reason" value={trade.exit_reason?label(trade.exit_reason):"Unavailable"}/></div></section>
  <section className="mt-6"><p className="eyebrow">Initial plan</p><div className="mt-3 grid grid-cols-2 gap-5 sm:grid-cols-4"><DetailMetric title="Stop" value={money(trade.initial_stop)}/><DetailMetric title="Target 1" value={money(trade.target_1)}/><DetailMetric title="Target 2" value={money(trade.target_2)}/><DetailMetric title="Target 3" value={money(trade.target_3)}/></div></section>
  <Timeline trade={trade}/>{trade.missing_data.length>0&&<section className="mt-6 rounded-lg border border-slate-800 p-4"><p className="eyebrow">Unavailable canonical fields</p><p className="mt-2 text-[10px] leading-5 text-slate-500">{trade.missing_data.map(label).join(" · ")}</p></section>}<footer className="mt-6 text-[9px] uppercase tracking-wider text-slate-700">Source {trade.source_version||"unavailable"} · exact trade/lane identity</footer></aside></div>}

export function JournalDesk(){
  const [filters,setFilters]=useState(initialFilters);const [selected,setSelected]=useState<JournalTrade|null>(null);
  const query=useMemo(()=>{const params=new URLSearchParams({status:"CLOSED",limit:"200"});if(filters.lane!=="ALL")params.set("lane",filters.lane);if(filters.symbol!=="ALL")params.set("symbol",filters.symbol);if(filters.result!=="ALL")params.set("result",filters.result);if(filters.dateFrom)params.set("date_from",filters.dateFrom);if(filters.dateTo)params.set("date_to",filters.dateTo);return params.toString()},[filters]);
  const journal=useJournalData(query);const rows=journal.data?.trades||[];
  return <div className="mx-auto max-w-[1680px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow text-violet-300">OptionBeacon / Historical record</p><h1 className="mt-2 text-2xl font-semibold tracking-[-.035em] sm:text-3xl">Journal</h1><p className="mt-2 max-w-2xl text-xs leading-5 text-slate-500">Canonical OB and BROAD outcomes, lane economics, and exact-identity management history.</p></div><div className="flex items-center gap-3"><div className="hidden text-right sm:block"><p className="metric-label">Last journal update</p><p className="mt-1 text-[10px] text-slate-500">{journal.data?fullTimestamp(journal.data.as_of):"Awaiting data"}</p></div><button onClick={()=>journal.mutate()} className="flex items-center gap-2 rounded-lg border border-slate-700 bg-slate-900/60 px-3 py-2 text-[10px] font-bold uppercase tracking-[.11em] text-slate-300"><RefreshCw size={13}/>Refresh</button></div></header>
  <FiltersBar filters={filters} setFilters={setFilters}/>
  <section className="surface mt-5 overflow-hidden" aria-labelledby="performance-summary"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800 px-5 py-4"><div className="flex items-center gap-2"><TrendingUp size={15} className="text-violet-300"/><div><p className="eyebrow">Deployable lane history</p><h2 id="performance-summary" className="mt-1 text-base font-semibold">Performance summary</h2></div></div><div className="flex gap-2"><StatusBadge value="OB + BROAD"/><StatusBadge value={journal.data?.data_status||"LOADING"}/></div></header>{!journal.data&&!journal.error?<SummarySkeleton/>:journal.error?<div className="p-5 text-xs text-rose-200">Summary unavailable. Use retry below.</div>:journal.data&&<PerformanceSummary metrics={journal.data.summary}/>}</section>
  {journal.data&&<LanePerformance lanes={journal.data.lanes}/>}<section className="surface mt-5 overflow-hidden" aria-labelledby="history-heading"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800 px-5 py-4"><div className="flex items-center gap-2"><BookOpen size={15} className="text-violet-300"/><div><p className="eyebrow">Canonical completed trades</p><h2 id="history-heading" className="mt-1 text-base font-semibold">Trade history</h2></div></div>{journal.data&&<span className="text-[10px] text-slate-600">{journal.data.total_count} matching trades</span>}</header>{journal.error?<div className="p-4"><ErrorState label="Journal history" retry={()=>journal.mutate()}/></div>:!journal.data?<HistorySkeleton/>:rows.length===0?<div className="p-5"><EmptyState title="No historical trades">No completed trades match the selected filters.</EmptyState></div>:<><DesktopHistory trades={rows} select={setSelected}/><MobileHistory trades={rows} select={setSelected}/></>}</section>
  <footer className="mt-5 flex flex-wrap items-center gap-x-5 gap-y-2 text-[10px] text-slate-700"><span className="flex items-center gap-2"><Database size={12}/>Persisted, read-only data · refreshed every 45s</span><span className="flex items-center gap-2"><ShieldCheck size={12}/>MIRROR excluded from deployable performance</span><span className="flex items-center gap-2"><Activity size={12}/>Management joined by exact trade and lane</span><span className="flex items-center gap-2"><CalendarDays size={12}/>Date filters use persisted trade timestamps</span><span className="flex items-center gap-2"><Clock3 size={12}/>Timeline loads once per selected trade</span></footer>{selected&&<TradeDetail trade={selected} close={()=>setSelected(null)}/>}</div>;
}
