"use client";

import { Activity, Database, HeartPulse, Layers3, RadioTower, RefreshCw } from "lucide-react";
import { useActiveTrades, useRecentTrades, useSystemStatus, useTradeDeskHome } from "@/hooks/use-options-data";
import { label, money, number, percent, timestamp } from "@/lib/format";
import type { TradeRow } from "@/lib/types";
import { EmptyState, SectionError } from "./empty-state";
import { Metric } from "./metric";
import { StatusBadge } from "./status-badge";

function textMeta(trade: TradeRow, ...keys: string[]) {
  for (const key of keys) { const value=trade.metadata[key]; if (typeof value === "string" && value) return value; }
  return null;
}

function numberMeta(trade: TradeRow, key: string) {
  const value=trade.metadata[key]; return typeof value === "number" ? value : null;
}

function SessionSummary({ home }: { home: ReturnType<typeof useTradeDeskHome> }) {
  if(home.error) return <section><SectionError label="Today's session" retry={()=>home.mutate()}/></section>;
  if(!home.data) return <section aria-label="Loading session summary" className="surface p-5"><div className="skeleton h-5 w-40"/><div className="mt-5 grid grid-cols-2 gap-4 sm:grid-cols-4">{Array.from({length:8}).map((_,i)=><div key={i} className="skeleton h-12"/>)}</div></section>;
  const s=home.data.session;
  return <section className="surface overflow-hidden" aria-labelledby="session-heading"><header className="flex items-center justify-between border-b border-slate-800 px-5 py-4"><div><p className="eyebrow">Today&apos;s session</p><h2 id="session-heading" className="mt-1 text-base font-semibold">Authoritative persisted performance</h2></div><span className="text-[10px] text-slate-600">As of {timestamp(home.data.as_of)}</span></header><div className="grid grid-cols-2 gap-x-4 gap-y-6 p-5 sm:grid-cols-4 xl:grid-cols-8"><Metric label="Realized P&L" value={money(s.realized_pnl)} accent={(s.realized_pnl||0)>=0?"text-emerald-300":"text-rose-300"}/><Metric label="Unrealized P&L" value={money(s.unrealized_pnl)}/><Metric label="Total P&L" value={money(s.total_pnl)} accent={(s.total_pnl||0)>=0?"text-emerald-300":"text-rose-300"}/><Metric label="Trades" value={number(s.trades,0)}/><Metric label="Wins" value={number(s.wins,0)}/><Metric label="Losses" value={number(s.losses,0)}/><Metric label="Win rate" value={percent(s.win_rate)}/><Metric label="Active" value={number(s.active_trades,0)}/></div></section>;
}

function ActiveTrades({ response }: { response: ReturnType<typeof useActiveTrades> }) {
  return <section className="surface overflow-hidden" aria-labelledby="active-heading"><header className="flex items-center justify-between border-b border-slate-800 px-5 py-4"><div className="flex items-center gap-2"><RadioTower aria-hidden size={15} className="text-violet-300"/><div><p className="eyebrow">Active / actionable</p><h2 id="active-heading" className="mt-1 text-base font-semibold">Open trades requiring awareness</h2></div></div><StatusBadge value={response.data?.length ? "LIVE" : "WATCHING"}/></header><div className="p-5">{response.error?<SectionError label="Active trades" retry={()=>response.mutate()}/>:!response.data?<div className="space-y-3">{[1,2].map(i=><div key={i} className="skeleton h-20"/>)}</div>:response.data.length===0?<EmptyState title="No active trades">OptionBeacon is monitoring current opportunities.</EmptyState>:<div className="space-y-2">{response.data.map(trade=><article key={trade.id} className="grid gap-4 rounded-lg border border-slate-800 bg-slate-950/25 p-4 sm:grid-cols-[1.1fr_.8fr_.8fr_.8fr] sm:items-center"><div><div className="flex items-center gap-2"><strong className="text-sm tracking-wide">{trade.symbol||"Unknown symbol"}</strong><StatusBadge value={trade.direction}/><StatusBadge value={trade.status}/></div><p className="mt-2 text-[10px] text-slate-500">{label(textMeta(trade,"execution_lane","variant","source_strategy")||trade.setup)}</p></div><Metric label="Entry / current" value={`${money(trade.entry_price)} / ${money(trade.last_price)}`}/><Metric label="Contract" value={textMeta(trade,"option_symbol","contract")||"Unavailable"}/><Metric label="Unrealized P&L" value={money(numberMeta(trade,"unrealized_pnl"))}/></article>)}</div>}</div></section>;
}

function LaneOverview({ home }: { home: ReturnType<typeof useTradeDeskHome> }) {
  return <section className="surface overflow-hidden" aria-labelledby="lanes-heading"><header className="flex items-center gap-2 border-b border-slate-800 px-5 py-4"><Layers3 aria-hidden size={15} className="text-violet-300"/><div><p className="eyebrow">Strategy / lane overview</p><h2 id="lanes-heading" className="mt-1 text-base font-semibold">Current participation</h2></div></header><div className="p-5">{home.error?<SectionError label="Lane overview" retry={()=>home.mutate()}/>:!home.data?<div className="grid gap-3 md:grid-cols-3">{[1,2,3].map(i=><div key={i} className="skeleton h-28"/>)}</div>:<div className="grid gap-3 md:grid-cols-3">{home.data.lanes.map(lane=><article key={lane.key} className={`rounded-lg border p-4 ${lane.role==="RESEARCH_CONTROL"?"border-cyan-400/15 bg-cyan-400/[.025]":"border-slate-800 bg-slate-950/25"}`}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold tracking-wide text-slate-200">{lane.label}</p><p className="mt-1 text-[10px] font-semibold uppercase tracking-[.12em] text-slate-600">{label(lane.role)}</p></div>{lane.role==="RESEARCH_CONTROL"&&<StatusBadge value="SHADOW"/>}</div><p className="mt-3 min-h-8 text-[10px] leading-4 text-slate-500">{lane.description}</p><div className="mt-4 grid grid-cols-3 gap-2"><Metric label="Active" value={number(lane.active_trades,0)}/><Metric label="Today" value={number(lane.trades_today,0)}/><Metric label="Realized" value={money(lane.realized_pnl)}/></div></article>)}</div>}</div></section>;
}

function RecentActivity({ response }: { response: ReturnType<typeof useRecentTrades> }) {
  return <section className="surface overflow-hidden" aria-labelledby="activity-heading"><header className="flex items-center gap-2 border-b border-slate-800 px-5 py-4"><Activity aria-hidden size={15} className="text-violet-300"/><div><p className="eyebrow">Recent activity</p><h2 id="activity-heading" className="mt-1 text-base font-semibold">Persisted trade events</h2></div></header><div className="p-5">{response.error?<SectionError label="Recent activity" retry={()=>response.mutate()}/>:!response.data?<div className="space-y-2">{[1,2,3].map(i=><div key={i} className="skeleton h-11"/>)}</div>:response.data.length===0?<EmptyState title="No recent activity">No persisted trade events are available.</EmptyState>:<div className="divide-y divide-slate-800/70">{response.data.map(trade=>{const closed=trade.status.toUpperCase()==="CLOSED"; return <div key={trade.id} className="grid grid-cols-[72px_1fr_auto] items-center gap-3 py-3 first:pt-0 last:pb-0"><span className="font-mono text-[10px] text-slate-600">{timestamp(closed?trade.closed_at:trade.opened_at).replace(/:\d{2} /," ")}</span><div className="flex min-w-0 items-center gap-2"><strong className="text-xs">{trade.symbol||"—"}</strong><StatusBadge value={trade.direction}/><span className="truncate text-[10px] text-slate-500">{label(textMeta(trade,"execution_lane","variant","source_strategy")||trade.setup)}</span></div><div className="text-right"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{closed?"Closed":"Opened"}</p><p className={`mt-1 font-mono text-xs ${(trade.realized_result||0)>=0?"text-emerald-300":"text-rose-300"}`}>{closed?money(trade.realized_result):money(trade.entry_price)}</p></div></div>})}</div>}</div></section>;
}

function SystemPanel({ system }: { system: ReturnType<typeof useSystemStatus> }) {
  return <section className="surface overflow-hidden" aria-labelledby="system-heading"><header className="flex items-center gap-2 border-b border-slate-800 px-5 py-4"><HeartPulse aria-hidden size={15} className="text-violet-300"/><div><p className="eyebrow">System status</p><h2 id="system-heading" className="mt-1 text-base font-semibold">Operational summary</h2></div></header><div className="p-5">{system.error?<SectionError label="System status" retry={()=>system.mutate()}/>:!system.data?<div className="skeleton h-24"/>:<div className="grid grid-cols-2 gap-5"><Metric label="API" value={label(system.data.status)}/><Metric label="Market" value={label(system.data.market_status)}/><Metric label="Database" value={label(system.data.database)}/><Metric label="Data" value={label(system.data.data_freshness)}/><Metric label="Worker" value={label(system.data.worker_status)}/><Metric label="Last success" value={timestamp(system.data.worker_last_success)}/></div>}</div></section>;
}

export function TradeDesk() {
  const home=useTradeDeskHome(); const active=useActiveTrades(); const recent=useRecentTrades(); const system=useSystemStatus();
  const refresh=()=>Promise.all([home.mutate(),active.mutate(),recent.mutate(),system.mutate()]);
  return <div className="mx-auto max-w-[1680px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><div className="mb-6 flex items-end justify-between gap-4"><div><p className="eyebrow text-violet-300">OptionBeacon / Home</p><h1 className="mt-2 text-2xl font-semibold tracking-[-.035em] sm:text-3xl">Trade Desk</h1><p className="mt-2 max-w-xl text-xs leading-5 text-slate-500">The command center for current participation, session performance, active trades, and system health.</p></div><button onClick={refresh} className="flex shrink-0 items-center gap-2 rounded-lg border border-slate-700 bg-slate-900/60 px-3 py-2 text-[10px] font-bold uppercase tracking-[.11em] text-slate-300 hover:border-slate-500"><RefreshCw aria-hidden size={13}/>Refresh</button></div><SessionSummary home={home}/><div className="mt-5"><ActiveTrades response={active}/></div><div className="mt-5"><LaneOverview home={home}/></div><div className="mt-5 grid items-start gap-5 xl:grid-cols-[1.6fr_.8fr]"><RecentActivity response={recent}/><SystemPanel system={system}/></div><footer className="mt-5 flex items-center gap-2 text-[10px] text-slate-700"><Database aria-hidden size={12}/>Persisted, read-only state. Provider calls and trading actions remain outside the React request path.</footer></div>;
}
