"use client";

import {Activity,Clock3,Database,HeartPulse,RefreshCw,ScanSearch,ShieldCheck,WifiOff} from "lucide-react";
import {useLiveSnapshot} from "@/hooks/use-options-data";
import {label,money,number,timestamp} from "@/lib/format";
import type {ActiveTrade,LiveSnapshot,LiveSymbolSnapshot,TradeRow} from "@/lib/types";
import {EmptyState} from "./empty-state";
import {Metric} from "./metric";
import {StatusBadge} from "./status-badge";

const indicatorName=(key:string)=>key.replaceAll("_"," ").replace(/\bema\b/i,"EMA").replace(/\brsi\b/i,"RSI").replace(/\bvwap\b/i,"VWAP");
const outcomeTone=(value?:number|null)=>value==null?"text-slate-300":value>=0?"text-emerald-300":"text-rose-300";

function TerminalHeader({data,degraded,refreshing,refresh}:{data:LiveSnapshot;degraded:boolean;refreshing:boolean;refresh:()=>void}){
 return <><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow text-violet-300">OptionBeacon / Trading terminal</p><h1 className="mt-2 text-2xl font-semibold tracking-[-.035em] sm:text-3xl">Market Command</h1><p className="mt-2 text-xs text-slate-500">Authoritative persisted decisions · snapshot {data.snapshot_id}</p></div><button onClick={refresh} disabled={refreshing} className="flex items-center gap-2 rounded-lg border border-slate-700 bg-slate-900/60 px-3 py-2 text-[10px] font-bold uppercase tracking-[.11em] text-slate-300 disabled:opacity-50"><RefreshCw size={13} className={refreshing?"animate-spin":""}/>Refresh</button></div>
 <section aria-label="Terminal status" className="mt-5 grid gap-px overflow-hidden rounded-xl border border-slate-800 bg-slate-800 sm:grid-cols-3 xl:grid-cols-6">{[["Connection",degraded?"Degraded":"Connected"],["Market",data.market.session_state],["Freshness",data.market.freshness],["Scanner",data.scanner.status],["Worker",data.system.state.worker_status],["Updated",timestamp(data.generated_at)]].map(([k,v])=><div key={k} className="bg-[#0c111d] px-4 py-3"><p className="metric-label">{k}</p><p className="mt-1 text-xs font-semibold text-slate-200">{label(v)}</p></div>)}</section>
 {(degraded||data.market.freshness==="stale"||data.system.stale_or_missing.length>0)&&<div role="alert" className="mt-3 flex items-center gap-2 rounded-lg border border-amber-400/20 bg-amber-400/[.06] px-4 py-3 text-xs text-amber-100">{degraded?<WifiOff size={14}/>:<Clock3 size={14}/>} {degraded?"Backend connection degraded. Showing the last valid authoritative snapshot.":`Snapshot needs attention: ${data.system.stale_or_missing.join(", ")||"stale data"}.`}</div>}</>;
}

function SetupCard({item}:{item:LiveSymbolSnapshot}){
 const observation=item.observation; const decisions=item.latest_decisions.filter(d=>d.data_status==="persisted");
 const primary=decisions.find(d=>d.state==="TAKE")||decisions[0];
 const state=primary?.state||observation?.qualification_state||item.scanner.signal_state||"UNAVAILABLE";
 const indicators=Object.entries(observation?.indicators||{}).filter(([,v])=>v!==null&&v!==undefined).slice(0,10);
 const price=observation?.underlying_price??item.scanner.underlying_price;
 const score=observation?.total_score??item.scanner.score;
 return <article data-testid={`setup-${item.symbol}`} className={`surface overflow-hidden ${state==="TAKE"?"ring-1 ring-emerald-400/25":state==="BLOCKED"||state==="REJECTED"?"ring-1 ring-rose-400/20":""}`}><header className="flex items-start justify-between border-b border-slate-800 px-5 py-4"><div><div className="flex items-center gap-2"><h2 className="text-xl font-black tracking-tight">{item.symbol}</h2><StatusBadge value={item.scanner.direction}/></div><p className="mt-1 text-[10px] text-slate-500">Observed {timestamp(observation?.observed_at??item.scanner.observed_at)}</p></div><div className="flex items-center gap-2"><StatusBadge value={item.scanner.freshness}/><StatusBadge value={state}/></div></header>
 <div className="p-5"><div className="grid grid-cols-3 gap-4"><Metric label="Persisted price" value={money(price)}/><Metric label="Setup" value={label(item.scanner.setup)}/><Metric label="Score" value={number(score,1)}/></div>
 <div className="mt-5"><p className="metric-label">Decision rationale</p><p className="mt-2 text-xs font-semibold text-slate-200">{label(primary?.reason_code??observation?.reason_code)}</p><p className="mt-1 text-xs leading-5 text-slate-500">{primary?.explanation??(observation?.explanation as string|undefined)??"No authoritative decision explanation is available."}</p></div>
 {indicators.length>0?<div className="mt-5 grid grid-cols-2 gap-x-5 gap-y-3 border-t border-slate-800 pt-4 sm:grid-cols-5">{indicators.map(([key,v])=><Metric key={key} label={indicatorName(key)} value={number(v,3)}/>)}</div>:<p className="mt-5 border-t border-slate-800 pt-4 text-[11px] text-slate-600">Persisted indicator values unavailable. Nothing has been reconstructed in the browser.</p>}
 <div className="mt-4 flex items-center gap-2 text-[10px] text-slate-600"><ShieldCheck size={12}/>{observation?`Provenance ${observation.observation_id}`:"Canonical observation unavailable"}</div></div></article>;
}

function DecisionFeed({data}:{data:LiveSnapshot}){return <section className="surface overflow-hidden"><header className="flex items-center gap-2 border-b border-slate-800 px-5 py-4"><ScanSearch size={15} className="text-violet-300"/><div><p className="eyebrow">Decision feed</p><h2 className="mt-1 text-sm font-semibold">Recent authoritative decisions</h2></div></header><div className="overflow-x-auto p-5">{data.decisions.length===0?<EmptyState title="No recent decisions">No persisted lane decision is available.</EmptyState>:<table className="w-full min-w-[620px] text-left text-xs"><thead className="text-[10px] uppercase tracking-wider text-slate-600"><tr><th className="pb-3">Time</th><th>Symbol</th><th>Lane</th><th>Setup</th><th>Action</th><th>Score</th><th>Reason</th><th>Provenance</th></tr></thead><tbody>{data.decisions.map((row,i)=><tr key={row.decision_id??`${row.opportunity_id}:${i}`} className="border-t border-slate-800"><td className="py-3 font-mono text-slate-500">{timestamp(row.timestamp).replace(/:\d{2} /," ")}</td><td className="font-bold">{row.symbol}</td><td>{row.lane}</td><td>{label(row.setup)} · {label(row.direction)}</td><td><StatusBadge value={row.action}/></td><td>{number(row.score,1)}</td><td><span className="font-semibold text-slate-300">{label(row.reason_code)}</span></td><td className="text-slate-600">{row.observation_id?"Linked":"Unavailable"}</td></tr>)}</tbody></table>}</div></section>}

function Positions({trades}:{trades:ActiveTrade[]}){return <section className="surface overflow-hidden"><header className="flex items-center gap-2 border-b border-slate-800 px-5 py-4"><Activity size={15} className="text-violet-300"/><div><p className="eyebrow">Active positions</p><h2 className="mt-1 text-sm font-semibold">Persisted lifecycle state</h2></div></header><div className="p-5">{trades.length===0?<EmptyState title="No active positions">The authoritative engine has no open positions.</EmptyState>:<div className="space-y-2">{trades.map(t=><article key={t.id} className="rounded-lg border border-slate-800 bg-slate-950/25 p-4"><div className="flex flex-wrap items-center gap-2"><strong>{t.symbol||"Unknown"}</strong><StatusBadge value={t.direction}/><StatusBadge value={t.status}/><span className="ml-auto font-mono text-[9px] text-slate-600">{t.id}</span></div><div className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-4"><Metric label="Entry / mark" value={`${money(t.underlying_entry??t.entry_price)} / ${money(t.latest_underlying??t.last_price)}`}/><Metric label="Stop / target" value={`${money(t.stop)} / ${money(t.target_1)}`}/><Metric label="Hold" value={t.time_in_trade_seconds==null?"Unavailable":`${Math.floor(t.time_in_trade_seconds/60)}m`}/><Metric label="Persisted P&L" value={money(t.unrealized_pnl)} accent={outcomeTone(t.unrealized_pnl)}/><Metric label="Breakeven" value={label(t.breakeven_state)}/><Metric label="Management" value={label(t.management_data_status)}/></div></article>)}</div>}</div></section>}

function RecentTrades({trades}:{trades:TradeRow[]}){return <section className="surface overflow-hidden"><header className="flex items-center gap-2 border-b border-slate-800 px-5 py-4"><Activity size={15} className="text-violet-300"/><div><p className="eyebrow">Recent trades</p><h2 className="mt-1 text-sm font-semibold">Compact authoritative history</h2></div></header><div className="p-5">{trades.length===0?<EmptyState title="No recent trades">No completed authoritative trade is available.</EmptyState>:<div className="divide-y divide-slate-800">{trades.slice(0,8).map(t=><div key={t.id} className="grid grid-cols-[70px_1fr_auto] items-center gap-3 py-3"><span className="font-mono text-[10px] text-slate-600">{timestamp(t.closed_at??t.opened_at).replace(/:\d{2} /," ")}</span><div><strong className="text-xs">{t.symbol??"Unknown"}</strong><span className="ml-2 text-[10px] text-slate-500">{label(t.direction)} · {label(t.exit_reason??t.status)}</span></div><span className={`font-mono text-xs ${outcomeTone(t.realized_result)}`}>{money(t.realized_result)}</span></div>)}</div>}</div></section>}

function Health({data}:{data:LiveSnapshot}){const s=data.system.state;return <section className="surface p-5"><div className="flex items-center gap-2"><HeartPulse size={15} className="text-violet-300"/><h2 className="text-sm font-semibold">System & provenance</h2></div><div className="mt-5 grid grid-cols-2 gap-5"><Metric label="Database" value={label(s.database)}/><Metric label="Worker" value={label(s.worker_status)}/><Metric label="Cycle" value={data.scanner.cycle_id??"Unavailable"}/><Metric label="Completion" value={label(data.scanner.cycle_completion_state)}/><Metric label="Last success" value={timestamp(data.scanner.last_successful_completed_cycle)}/><Metric label="Provenance" value={label(data.provenance.data_status)}/><Metric label="SPY coverage" value={label(data.system.coverage.SPY)}/><Metric label="QQQ coverage" value={label(data.system.coverage.QQQ)}/></div></section>}

export function TradeDesk(){const snapshot=useLiveSnapshot();if(snapshot.isLoading&&!snapshot.data)return <div aria-label="Loading trading terminal" className="mx-auto max-w-[1680px] p-6"><div className="skeleton h-24"/><div className="mt-5 grid gap-5 xl:grid-cols-2"><div className="skeleton h-72"/><div className="skeleton h-72"/></div></div>;if(snapshot.error&&!snapshot.data)return <div role="alert" className="m-6 surface p-8 text-center"><WifiOff className="mx-auto text-rose-300"/><h1 className="mt-4 text-xl font-bold">OptionBeacon backend disconnected</h1><p className="mt-2 text-sm text-slate-500">No authoritative snapshot is available. Trading values are intentionally hidden.</p><button onClick={()=>snapshot.mutate()} className="mt-5 rounded border border-slate-700 px-4 py-2 text-xs">Retry</button></div>;const data=snapshot.data!;return <div className="mx-auto max-w-[1680px] px-4 py-6 sm:px-6 lg:px-8"><TerminalHeader data={data} degraded={Boolean(snapshot.error)} refreshing={snapshot.isValidating} refresh={()=>snapshot.mutate()}/><div className="mt-5 grid gap-5 xl:grid-cols-2"><SetupCard item={data.symbols.SPY}/><SetupCard item={data.symbols.QQQ}/></div><div className="mt-5 grid items-start gap-5 2xl:grid-cols-[1.35fr_1fr]"><DecisionFeed data={data}/><Positions trades={data.active_trades}/></div><div className="mt-5 grid items-start gap-5 xl:grid-cols-[1.35fr_.65fr]"><RecentTrades trades={data.recent_trades}/><Health data={data}/></div><footer className="mt-5 flex items-center gap-2 text-[10px] text-slate-700"><Database size={12}/>Presentation only. No provider calls, strategy evaluation, or trading actions occur in this interface.</footer></div>}
