import type {LiveSnapshot,SystemStatus} from "@/lib/types";

export const system:SystemStatus={status:"ok",market_status:"open",database:"connected",data_freshness:"fresh",worker_status:"healthy",worker_last_success:"2026-09-13T14:30:00Z",provider_status:"not_queried",timestamp:"2026-09-13T14:30:00Z"};
const scanner=(symbol:"SPY"|"QQQ")=>({symbol,data_status:"persisted",underlying_price:symbol==="SPY"?650.25:null,direction:symbol==="SPY"?"CALL":"PUT",setup:symbol==="SPY"?"VWAP_CONTINUATION":"BREAKDOWN",score:symbol==="SPY"?84:null,confidence:.8,signal_state:symbol==="SPY"?"OPEN":"BLOCKED",observed_at:"2026-09-13T14:30:00Z",signal_age_seconds:30,freshness:"fresh",actionable:symbol==="SPY",context:{}});

export const snapshot:LiveSnapshot={
 schema_version:"1",snapshot_id:"a1b2c3d4e5f607182930",generated_at:"2026-09-13T14:30:00Z",data_status:"persisted",
 market:{session_date:"2026-09-13",session_state:"open",last_authoritative_data_at:"2026-09-13T14:30:00Z",freshness:"fresh"},
 symbols:{
  SPY:{symbol:"SPY",data_status:"persisted",observation:{observation_id:"obs-spy",scan_cycle_id:"cycle-42",observed_at:"2026-09-13T14:30:00Z",underlying_price:650.25,direction:"CALL",qualification_state:"TAKE",reason_code:"ALL_RISK_CONTROLS_PASSED",total_score:84,indicators:{ema_9:649.8,ema_21:648.2,rsi_14:61.4,vwap:649.1}},scanner:scanner("SPY"),latest_decisions:[{lane:"OB",data_status:"persisted",decision_id:"decision-spy",state:"TAKE",reason_code:"ALL_RISK_CONTROLS_PASSED",explanation:"Persisted controls passed.",proposed_contract:null,proposed_quantity:2,proposed_capital_required:220,proposed_dollar_risk:55,proposed_account_risk_pct:.22,decided_at:"2026-09-13T14:30:00Z"}]},
  QQQ:{symbol:"QQQ",data_status:"persisted",observation:{observation_id:"obs-qqq",scan_cycle_id:"cycle-42",observed_at:"2026-09-13T14:30:00Z",underlying_price:null,direction:"PUT",qualification_state:"REJECTED",reason_code:"CONTRACT_SPREAD_TOO_WIDE",total_score:null,indicators:{}},scanner:scanner("QQQ"),latest_decisions:[{lane:"OB",data_status:"persisted",decision_id:"decision-qqq",state:"REJECTED",reason_code:"CONTRACT_SPREAD_TOO_WIDE",explanation:"Persisted spread check blocked entry.",proposed_contract:null,proposed_quantity:null,proposed_capital_required:null,proposed_dollar_risk:null,proposed_account_risk_pct:null,decided_at:"2026-09-13T14:29:00Z"}]}
 },
 scanner:{cycle_id:"cycle-42",cycle_timestamp:"2026-09-13T14:29:30Z",cycle_completion_state:"COMPLETED",latest_processed_symbols:["SPY","QQQ"],status:"CURRENT",last_successful_completed_cycle:"2026-09-13T14:30:00Z",health:{state:"CURRENT",message:"Current",market_data_state:"AVAILABLE",worker_status:"healthy",provider_status:"not_queried",data_freshness:"fresh",last_started_at:"2026-09-13T14:29:30Z",last_completed_at:"2026-09-13T14:30:00Z",last_success_at:"2026-09-13T14:30:00Z",last_error_at:null,last_error_message:null,scan_duration_seconds:30,symbols_processed:2,symbols_attempted:2,symbol_count:2,results:2,failures:0,expected_interval_seconds:300,next_expected_at:"2026-09-13T14:35:00Z"}},
 decisions:[{decision_id:"decision-spy",opportunity_id:"opp-spy",symbol:"SPY",lane:"OB",timestamp:"2026-09-13T14:30:00Z",action:"TAKE",score:84,setup:"VWAP_CONTINUATION",direction:"CALL",reason_code:"ALL_RISK_CONTROLS_PASSED",explanation:"Persisted controls passed.",observation_id:"obs-spy",scan_cycle_id:"cycle-42"},{decision_id:"decision-qqq",opportunity_id:"opp-qqq",symbol:"QQQ",lane:"OB",timestamp:"2026-09-13T14:29:00Z",action:"REJECTED",score:null,setup:"BREAKDOWN",direction:"PUT",reason_code:"CONTRACT_SPREAD_TOO_WIDE",explanation:"Persisted spread check blocked entry.",observation_id:"obs-qqq",scan_cycle_id:"cycle-42"}],
 active_trades:[{id:"trade-1",opportunity_id:"opp-spy",symbol:"SPY",direction:"CALL",setup:"VWAP_CONTINUATION",status:"OPEN",opened_at:"2026-09-13T14:10:00Z",closed_at:null,entry_price:650,last_price:651,exit_price:null,realized_result:null,exit_reason:null,metadata:{},lane:"OB",lane_role:"AUTHORITATIVE",strategy:"VWAP_CONTINUATION",data_status:"persisted",contract_symbol:"SPY-C",strike:651,option_type:"CALL",expiration:"2026-09-13",dte:0,quantity:2,entry_timestamp:"2026-09-13T14:10:00Z",underlying_entry:650,option_entry_premium:1.2,capital_committed:240,initial_dollar_risk:55,account_risk_pct:.22,current_dollar_risk:30,latest_underlying:651,latest_option_mark:1.35,unrealized_pnl:30,unrealized_return_pct:12.5,time_in_trade_seconds:1200,data_freshness:"fresh",mark_timestamp:"2026-09-13T14:30:00Z",stop:649,target_1:652,target_2:653,target_3:null,breakeven_state:"PROTECTED",maximum_hold_minutes:45,exit_score:20,exit_label:"HOLD",exit_state:"HOLD",trade_coach_state:"HOLD",trade_coach_status:"HOLD",thesis_state:"INTACT",thesis_status:"INTACT",momentum_state:"HEALTHY",structure_state:"INTACT",target_progress:"APPROACHING_T1",stop_management_state:"BREAKEVEN",management_reason:"Persisted management",management_updated_at:"2026-09-13T14:30:00Z",last_management_update:"2026-09-13T14:30:00Z",management_data_status:"persisted"}],
 recent_trades:[{id:"trade-0",opportunity_id:"opp-0",symbol:"QQQ",direction:"PUT",setup:"BREAKDOWN",status:"CLOSED",opened_at:"2026-09-13T13:30:00Z",closed_at:"2026-09-13T13:55:00Z",entry_price:580,exit_price:578,last_price:578,realized_result:75,exit_reason:"TARGET",metadata:{}}],
 system:{state:system,coverage:{SPY:"persisted",QQQ:"persisted"},provenance:{},stale_or_missing:[]},provenance:{data_status:"persisted",observation_count:2,schema:"canonical_decision_observations"}
};
