import http from "node:http";

const strategy=(symbol,direction,contract)=>({symbol,price:symbol==="SPY"?642.18:571.42,market_status:"open",data_status:"persisted",last_updated:new Date().toISOString(),bias:{direction,label:`${direction} BIAS`},trade_coverage:{direction,entry_trigger:symbol==="SPY"?642.25:571.2,state:symbol==="SPY"?"READY":"WATCHING"},setup:{state:contract?"selected":"awaiting_contract",strike:contract?643:null,expiration:contract?"2026-08-24":null,dte:contract?0:null,spread:contract?3.5:null,contract},context:{level:"available",known_factors:["vwap_aligned","ema_aligned"],details:null},confirmations:{state:"context_only",items:["EMA aligned"]},market_condition:{regime:"RANGE / CHOP"},session:{pnl:null,trades:0,wins:0,losses:0,win_rate:null}});
const activeTrade={id:"active-1",opportunity_id:"opp-1",symbol:"SPY",direction:"CALL",setup:"ORB",status:"OPEN",opened_at:new Date().toISOString(),closed_at:null,entry_price:1.2,last_price:1.35,exit_price:null,realized_result:null,exit_reason:null,metadata:{execution_lane:"BROAD",option_symbol:"SPY260824C00643000",unrealized_pnl:15}};
const closedTrade={id:"closed-1",opportunity_id:"opp-2",symbol:"QQQ",direction:"PUT",setup:"MIRROR_CONTROL",status:"CLOSED",opened_at:new Date(Date.now()-30*60_000).toISOString(),closed_at:new Date(Date.now()-10*60_000).toISOString(),entry_price:1.4,last_price:1.2,exit_price:1.15,realized_result:25,exit_reason:"TARGET",metadata:{}};
const routes={
  "/api/trade-desk":{as_of:new Date().toISOString(),data_status:"persisted",session:{realized_pnl:25,unrealized_pnl:15,total_pnl:40,trades:2,wins:1,losses:0,win_rate:100,active_trades:1},active:[],recent_activity:[],accounts:[{lane:"OB",data_status:"persisted",starting_capital:25000,current_equity:25640,cash_available:24400,capital_committed:1240,net_pnl:640,return_pct:2.56,realized_pnl:600,unrealized_pnl:40,fees:12,slippage:18,peak_equity:25800,current_drawdown_pct:.62,maximum_drawdown_pct:3.4,daily_pnl:90,open_risk:240,open_positions:2,risk_state:"NORMAL",readiness_status:"DEVELOPING",metrics:{trades:44,rejected_opportunities:7},updated_at:new Date().toISOString()},{lane:"BROAD",data_status:"persisted",starting_capital:25000,current_equity:25120,cash_available:25120,capital_committed:0,net_pnl:120,return_pct:.48,realized_pnl:120,unrealized_pnl:0,fees:8,slippage:14,peak_equity:25300,current_drawdown_pct:.71,maximum_drawdown_pct:4.1,daily_pnl:25,open_risk:0,open_positions:0,risk_state:"WARNING",readiness_status:"EARLY_RESEARCH",metrics:{trades:22,rejected_opportunities:13},updated_at:new Date().toISOString()}],capital_decisions:[{decision_id:"d-1",lane:"OB",opportunity_id:"opp-1",symbol:"SPY",direction:"CALL",state:"TAKE",reason_code:"ALL_RISK_CONTROLS_PASSED",explanation:"Setup qualifies and all simulated-capital risk controls passed.",proposed_contract:"SPY260824C00643000",proposed_quantity:8,proposed_capital_required:1136,proposed_dollar_risk:112,proposed_account_risk_pct:.45,decided_at:new Date().toISOString()}],lanes:[{key:"OB",label:"OB",role:"AUTHORITATIVE",active_trades:0,trades_today:1,realized_pnl:25,description:"Authoritative OptionBeacon strategy"},{key:"BROAD",label:"BROAD",role:"PAPER",active_trades:1,trades_today:1,realized_pnl:null,description:"Broad-universe paper participation"},{key:"CONTROL_RESEARCH",label:"MIRROR / CONTROL RESEARCH",role:"RESEARCH_CONTROL",active_trades:0,trades_today:0,realized_pnl:null,description:"Research/control comparison only; not a primary live lane"}]},
  "/api/trades/active":[activeTrade],
  "/api/trades/recent?limit=12":[closedTrade],
  "/api/options-desk/SPY":strategy("SPY","CALL","SPY260824C00643000"),
  "/api/options-desk/QQQ":strategy("QQQ","PUT",null),
  "/api/scalp/SPY":{symbol:"SPY",strategy:"SCALP_RESEARCH",mode:"SHADOW",market_status:"open",data_status:"persisted",current:{direction:"CALL",setup_family:"VWAP_CONTINUATION",state:"FORMING",probability:.66,entry_trigger:642.3,invalidation:641.9,maximum_chase:642.5,expected_move:.34,expected_hold_minutes:[3,15]}},
  "/api/scalp/QQQ":{symbol:"QQQ",strategy:"SCALP_RESEARCH",mode:"SHADOW",market_status:"open",data_status:"unavailable",current:null},
  "/api/scalp/SPY/performance":{symbol:"SPY",strategy:"SCALP_RESEARCH",metrics:{triggered_trades:8,win_rate:50,expectancy:3,profit_factor:1.1,net_simulated_pnl:24,maximum_drawdown:40,average_hold_minutes:6,evidence:"INSUFFICIENT"}},
  "/api/scalp/QQQ/performance":{symbol:"QQQ",strategy:"SCALP_RESEARCH",metrics:{triggered_trades:7,win_rate:42.8,expectancy:-1.2,profit_factor:.9,net_simulated_pnl:-8.4,maximum_drawdown:52,average_hold_minutes:7,evidence:"INSUFFICIENT"}},
  "/api/scalp/compare":{strategy:"SCALP_RESEARCH",symbols:{SPY:{triggered_trades:8,win_rate:50,expectancy:3,profit_factor:1.1,net_simulated_pnl:24,maximum_drawdown:40,average_hold_minutes:6,evidence:"INSUFFICIENT"},QQQ:{triggered_trades:7,win_rate:42.8,expectancy:-1.2,profit_factor:.9,net_simulated_pnl:-8.4,maximum_drawdown:52,average_hold_minutes:7,evidence:"INSUFFICIENT"}},normalization:"per triggered contract; realistic P&L primary"},
  "/api/system/status":{status:"ok",market_status:"open",database:"connected",data_freshness:"fresh",worker_status:"healthy",worker_last_success:new Date().toISOString(),provider_status:"not_queried",timestamp:new Date().toISOString()},
};

http.createServer((request,response)=>{const body=routes[request.url];response.setHeader("Access-Control-Allow-Origin","http://localhost:3000");response.setHeader("Content-Type","application/json");response.writeHead(body?200:404);response.end(JSON.stringify(body||{detail:"Not found"}))}).listen(8000,()=>console.log("OptionBeacon mock API on http://localhost:8000"));
