import http from "node:http";

const strategy=(symbol,direction,contract)=>({symbol,price:symbol==="SPY"?642.18:571.42,market_status:"open",data_status:"persisted",last_updated:new Date().toISOString(),bias:{direction,label:`${direction} BIAS`},trade_coverage:{direction,entry_trigger:symbol==="SPY"?642.25:571.2,state:symbol==="SPY"?"READY":"WATCHING"},setup:{state:contract?"selected":"awaiting_contract",strike:contract?643:null,expiration:contract?"2026-08-24":null,dte:contract?0:null,spread:contract?3.5:null,contract},context:{level:"available",known_factors:["vwap_aligned","ema_aligned"],details:null},confirmations:{state:"context_only",items:["EMA aligned"]},market_condition:{regime:"RANGE / CHOP"},session:{pnl:null,trades:0,wins:0,losses:0,win_rate:null}});
const managementUpdatedAt=new Date(Date.now()-30_000).toISOString();
const activeTrade={id:"OB:active-1",opportunity_id:"opp-1",symbol:"QQQ",direction:"CALL",setup:"VWAP_CONTINUATION",status:"OPEN",opened_at:new Date(Date.now()-7*60_000).toISOString(),closed_at:null,entry_price:713.1,last_price:713.8,exit_price:null,realized_result:null,exit_reason:null,metadata:{},lane:"OB",lane_role:"AUTHORITATIVE",strategy:"OB",data_status:"persisted",contract_symbol:"QQQ260824C00713000",strike:713,option_type:"CALL",expiration:"2026-08-24",dte:0,quantity:8,entry_timestamp:new Date(Date.now()-7*60_000).toISOString(),underlying_entry:713.1,option_entry_premium:1.42,capital_committed:1136,initial_dollar_risk:112,account_risk_pct:.45,current_dollar_risk:95,latest_underlying:713.8,latest_option_mark:1.61,unrealized_pnl:152,unrealized_return_pct:13.4,time_in_trade_seconds:420,data_freshness:"fresh",mark_timestamp:new Date(Date.now()-20_000).toISOString(),stop:712.6,target_1:714,target_2:714.8,target_3:715.5,breakeven_state:null,maximum_hold_minutes:null,exit_score:76,exit_label:"HOLD",exit_state:"HOLD",trade_coach_state:"THESIS_INTACT",trade_coach_status:"THESIS_INTACT",thesis_state:"INTACT",thesis_status:"INTACT",momentum_state:"MODERATING",structure_state:"ABOVE_VWAP",target_progress:"APPROACHING_T1",stop_management_state:null,management_reason:"STRUCTURE_HOLDING",management_updated_at:managementUpdatedAt,last_management_update:managementUpdatedAt,management_data_status:"persisted"};
const broadTrade={...activeTrade,id:"BROAD:active-2",opportunity_id:"opp-3",symbol:"SPY",contract_symbol:"SPY260824P00642000",strike:642,option_type:"PUT",direction:"PUT",lane:"BROAD",lane_role:"PAPER",strategy:"BROAD",quantity:3,underlying_entry:642.4,latest_underlying:642.7,option_entry_premium:1.18,latest_option_mark:null,unrealized_pnl:-24,unrealized_return_pct:-6.8,capital_committed:354,initial_dollar_risk:48,account_risk_pct:.19,current_dollar_risk:null,data_freshness:"stale",mark_timestamp:new Date(Date.now()-21*60_000).toISOString(),stop:643.1,target_1:641.8,target_2:641.2,target_3:null,exit_score:null,exit_label:null,exit_state:null,trade_coach_state:null,trade_coach_status:null,thesis_state:null,thesis_status:null,momentum_state:null,structure_state:null,target_progress:null,management_reason:null,management_updated_at:null,last_management_update:null,management_data_status:"unavailable"};
const journalTrade={trade_id:"OB:journal-1",opportunity_id:"opp-journal-1",lane:"OB",lane_role:"AUTHORITATIVE",symbol:"QQQ",direction:"CALL",status:"CLOSED",strategy:"VWAP continuation",contract_symbol:"QQQ260824C00713000",strike:713,option_type:"CALL",expiration:"2026-08-24",dte:0,quantity:2,entry_timestamp:new Date(Date.now()-42*60_000).toISOString(),underlying_entry:713.1,option_entry_premium:1.42,capital_committed:284,initial_dollar_risk:56,exit_timestamp:new Date(Date.now()-30*60_000).toISOString(),underlying_exit:714.2,option_exit_premium:1.62,exit_reason:"TARGET",hold_duration_seconds:720,realized_pnl:35,realized_return_pct:15.71,r_multiple:.625,mfe_dollars:52,mae_dollars:-18,mfe_pct:18.57,mae_pct:-6.43,result:"WIN",initial_stop:712.5,target_1:714,target_2:714.8,target_3:715.5,management_history_available:true,management_snapshot_count:2,final_exit_score:64,final_management_label:"PROTECT",final_management_at:new Date(Date.now()-32*60_000).toISOString(),data_quality:"CANONICAL",missing_data:[],source_version:"scanner-v7"};
const journalBroad={...journalTrade,trade_id:"BROAD:journal-2",opportunity_id:"opp-journal-2",lane:"BROAD",lane_role:"PAPER",symbol:"SPY",direction:"PUT",contract_symbol:"SPY260824P00642000",strike:642,option_type:"PUT",quantity:1,realized_pnl:-20,realized_return_pct:-7.01,result:"LOSS",exit_reason:"STOP",management_history_available:false,management_snapshot_count:0,final_exit_score:null,final_management_label:null,final_management_at:null,missing_data:["canonical_management_history"]};
const journalMetrics={total_trades:2,wins:1,losses:1,breakeven:0,win_rate:50,realized_pnl:15,average_winner:35,average_loser:-20,profit_factor:1.75,average_return_pct:4.35,average_hold_seconds:690};
const journalPayload={as_of:new Date().toISOString(),data_status:"persisted",total_count:2,limit:200,offset:0,summary:journalMetrics,lanes:[{lane:"OB",...journalMetrics,total_trades:1,wins:1,losses:0,win_rate:100,realized_pnl:35,average_return_pct:15.71,profit_factor:null},{lane:"BROAD",...journalMetrics,total_trades:1,wins:0,losses:1,win_rate:0,realized_pnl:-20,average_return_pct:-7.01,profit_factor:0}],control_research:null,trades:[journalTrade,journalBroad]};
const journalManagement=[{snapshot_id:"journal-snap-1",trade_id:journalTrade.trade_id,opportunity_id:journalTrade.opportunity_id,lane:"OB",lane_role:"AUTHORITATIVE",symbol:"QQQ",contract_symbol:journalTrade.contract_symbol,captured_at:new Date(Date.now()-38*60_000).toISOString(),source_timestamp:new Date(Date.now()-38*60_000).toISOString(),trade_status:"OPEN",quantity:2,entry_timestamp:journalTrade.entry_timestamp,entry_premium:1.42,latest_option_mark:1.51,latest_underlying:713.7,mark_timestamp:new Date(Date.now()-38*60_000).toISOString(),time_in_trade_seconds:240,current_stop:712.5,target_1:714,target_2:714.8,target_3:715.5,breakeven_state:null,maximum_hold_minutes:15,exit_score:28,exit_label:"HOLD",trade_coach_state:"THESIS_INTACT",thesis_state:"INTACT",momentum_state:"HEALTHY",structure_state:"ABOVE_VWAP",target_progress:"APPROACHING_T1",stop_management_state:"ORIGINAL",management_reason:"STRUCTURE_HOLDING",management_version:"mock-v1",management_source:"mock",unrealized_pnl:18,unrealized_return_pct:6.3,current_managed_risk:56,data_freshness:"fresh",stale:false,missing_data:[],state_fingerprint:"mock-1"},{snapshot_id:"journal-snap-2",trade_id:journalTrade.trade_id,opportunity_id:journalTrade.opportunity_id,lane:"OB",lane_role:"AUTHORITATIVE",symbol:"QQQ",contract_symbol:journalTrade.contract_symbol,captured_at:new Date(Date.now()-32*60_000).toISOString(),source_timestamp:new Date(Date.now()-32*60_000).toISOString(),trade_status:"OPEN",quantity:2,entry_timestamp:journalTrade.entry_timestamp,entry_premium:1.42,latest_option_mark:1.58,latest_underlying:714,mark_timestamp:new Date(Date.now()-32*60_000).toISOString(),time_in_trade_seconds:600,current_stop:713.3,target_1:714,target_2:714.8,target_3:715.5,breakeven_state:"ACTIVE",maximum_hold_minutes:15,exit_score:64,exit_label:"PROTECT",trade_coach_state:"THESIS_INTACT",thesis_state:"INTACT",momentum_state:"WEAKENING",structure_state:"ABOVE_VWAP",target_progress:"T1_REACHED",stop_management_state:"BREAKEVEN",management_reason:"MOMENTUM_WEAKENING",management_version:"mock-v1",management_source:"mock",unrealized_pnl:32,unrealized_return_pct:11.2,current_managed_risk:20,data_freshness:"fresh",stale:false,missing_data:[],state_fingerprint:"mock-2"}];
const closedTrade={id:"closed-1",opportunity_id:"opp-2",symbol:"QQQ",direction:"PUT",setup:"MIRROR_CONTROL",status:"CLOSED",opened_at:new Date(Date.now()-30*60_000).toISOString(),closed_at:new Date(Date.now()-10*60_000).toISOString(),entry_price:1.4,last_price:1.2,exit_price:1.15,realized_result:25,exit_reason:"TARGET",metadata:{}};
const scannerNow=new Date().toISOString();
const scannerOpportunity={opportunity_id:"opp-1",symbol:"SPY",direction:"Bullish",strategy:"VWAP continuation",observed_at:new Date(Date.now()-2*60_000).toISOString(),score:81,confidence:78,contract:"SPY260824C00643000",entry:642.25,stop:641.82,targets:[642.9,643.4],status:"OPEN",actionable:true,data_status:"persisted",freshness:"fresh",context:{regime:"range_chop"},lane_decisions:[{lane:"OB",data_status:"persisted",state:"TAKE",reason_code:"ALL_RISK_CONTROLS_PASSED",explanation:"Setup qualifies and all simulated-capital risk controls passed.",proposed_contract:"SPY260824C00643000",proposed_quantity:2,proposed_capital_required:228,proposed_dollar_risk:56,proposed_account_risk_pct:.22,decided_at:new Date(Date.now()-60_000).toISOString()},{lane:"BROAD",data_status:"persisted",state:"PASS",reason_code:"CONTRACT_SPREAD_TOO_WIDE",explanation:"Contract spread exceeds the BROAD lane limit.",proposed_contract:"SPY260824C00643000",proposed_quantity:0,proposed_capital_required:0,proposed_dollar_risk:0,proposed_account_risk_pct:0,decided_at:new Date(Date.now()-60_000).toISOString()}]};
const scannerPayload={as_of:scannerNow,market_status:"open",data_status:"persisted",research_control_role:"RESEARCH_CONTROL_ONLY",health:{state:"CURRENT",message:"Scanner data is current.",market_data_state:"AVAILABLE",worker_status:"healthy",provider_status:"not_queried",data_freshness:"fresh",last_started_at:new Date(Date.now()-90_000).toISOString(),last_completed_at:new Date(Date.now()-60_000).toISOString(),last_success_at:new Date(Date.now()-60_000).toISOString(),last_error_at:null,last_error_message:null,scan_duration_seconds:22.4,symbols_processed:74,symbols_attempted:74,symbol_count:74,results:74,failures:0,expected_interval_seconds:300,next_expected_at:new Date(Date.now()+4*60_000).toISOString()},instruments:[{symbol:"SPY",data_status:"persisted",underlying_price:642.31,direction:"Bullish",setup:"VWAP continuation",score:81,confidence:78,signal_state:"OPEN",observed_at:scannerOpportunity.observed_at,signal_age_seconds:120,freshness:"fresh",actionable:true,context:{regime:"range_chop"}},{symbol:"QQQ",data_status:"unavailable",underlying_price:null,direction:null,setup:null,score:null,confidence:null,signal_state:"UNAVAILABLE",observed_at:null,signal_age_seconds:null,freshness:"unavailable",actionable:false,context:{}}],opportunities:[scannerOpportunity],recent_activity:[{activity_id:"decision:ob-1",event_type:"LANE_DECISION",occurred_at:new Date(Date.now()-60_000).toISOString(),symbol:"SPY",direction:"CALL",opportunity_id:"opp-1",lane:"OB",status:"TAKE",reason_code:"ALL_RISK_CONTROLS_PASSED",description:"Setup qualifies and all simulated-capital risk controls passed."},{activity_id:"decision:broad-1",event_type:"LANE_DECISION",occurred_at:new Date(Date.now()-60_000).toISOString(),symbol:"SPY",direction:"CALL",opportunity_id:"opp-1",lane:"BROAD",status:"PASS",reason_code:"CONTRACT_SPREAD_TOO_WIDE",description:"Contract spread exceeds the BROAD lane limit."}],sections:[{section:"scanner_health",data_status:"persisted",message:null},{section:"opportunities",data_status:"persisted",message:null},{section:"lane_decisions",data_status:"persisted",message:null},{section:"recent_activity",data_status:"persisted",message:null}]};
const routes={
  "/api/trade-desk":{as_of:new Date().toISOString(),data_status:"persisted",session:{realized_pnl:25,unrealized_pnl:15,total_pnl:40,trades:2,wins:1,losses:0,win_rate:100,active_trades:1},active:[],recent_activity:[],accounts:[{lane:"OB",data_status:"persisted",starting_capital:25000,current_equity:25640,cash_available:24400,capital_committed:1240,net_pnl:640,return_pct:2.56,realized_pnl:600,unrealized_pnl:40,fees:12,slippage:18,peak_equity:25800,current_drawdown_pct:.62,maximum_drawdown_pct:3.4,daily_pnl:90,open_risk:240,open_positions:2,risk_state:"NORMAL",readiness_status:"DEVELOPING",metrics:{trades:44,rejected_opportunities:7},updated_at:new Date().toISOString()},{lane:"BROAD",data_status:"persisted",starting_capital:25000,current_equity:25120,cash_available:25120,capital_committed:0,net_pnl:120,return_pct:.48,realized_pnl:120,unrealized_pnl:0,fees:8,slippage:14,peak_equity:25300,current_drawdown_pct:.71,maximum_drawdown_pct:4.1,daily_pnl:25,open_risk:0,open_positions:0,risk_state:"WARNING",readiness_status:"EARLY_RESEARCH",metrics:{trades:22,rejected_opportunities:13},updated_at:new Date().toISOString()}],capital_decisions:[{decision_id:"d-1",lane:"OB",opportunity_id:"opp-1",symbol:"SPY",direction:"CALL",state:"TAKE",reason_code:"ALL_RISK_CONTROLS_PASSED",explanation:"Setup qualifies and all simulated-capital risk controls passed.",proposed_contract:"SPY260824C00643000",proposed_quantity:8,proposed_capital_required:1136,proposed_dollar_risk:112,proposed_account_risk_pct:.45,decided_at:new Date().toISOString()}],lanes:[{key:"OB",label:"OB",role:"AUTHORITATIVE",active_trades:0,trades_today:1,realized_pnl:25,description:"Authoritative OptionBeacon strategy"},{key:"BROAD",label:"BROAD",role:"PAPER",active_trades:1,trades_today:1,realized_pnl:null,description:"Broad-universe paper participation"},{key:"CONTROL_RESEARCH",label:"MIRROR / CONTROL RESEARCH",role:"RESEARCH_CONTROL",active_trades:0,trades_today:0,realized_pnl:null,description:"Research/control comparison only; not a primary live lane"}]},
  "/api/trades/active":[activeTrade,broadTrade],
  "/api/trades/recent?limit=12":[closedTrade],
  "/api/options-desk/SPY":strategy("SPY","CALL","SPY260824C00643000"),
  "/api/options-desk/QQQ":strategy("QQQ","PUT",null),
  "/api/scalp/SPY":{symbol:"SPY",strategy:"SCALP_RESEARCH",mode:"SHADOW",market_status:"open",data_status:"persisted",current:{direction:"CALL",setup_family:"VWAP_CONTINUATION",state:"FORMING",probability:.66,entry_trigger:642.3,invalidation:641.9,maximum_chase:642.5,expected_move:.34,expected_hold_minutes:[3,15]}},
  "/api/scalp/QQQ":{symbol:"QQQ",strategy:"SCALP_RESEARCH",mode:"SHADOW",market_status:"open",data_status:"unavailable",current:null},
  "/api/scalp/SPY/performance":{symbol:"SPY",strategy:"SCALP_RESEARCH",metrics:{triggered_trades:8,win_rate:50,expectancy:3,profit_factor:1.1,net_simulated_pnl:24,maximum_drawdown:40,average_hold_minutes:6,evidence:"INSUFFICIENT"}},
  "/api/scalp/QQQ/performance":{symbol:"QQQ",strategy:"SCALP_RESEARCH",metrics:{triggered_trades:7,win_rate:42.8,expectancy:-1.2,profit_factor:.9,net_simulated_pnl:-8.4,maximum_drawdown:52,average_hold_minutes:7,evidence:"INSUFFICIENT"}},
  "/api/scalp/compare":{strategy:"SCALP_RESEARCH",symbols:{SPY:{triggered_trades:8,win_rate:50,expectancy:3,profit_factor:1.1,net_simulated_pnl:24,maximum_drawdown:40,average_hold_minutes:6,evidence:"INSUFFICIENT"},QQQ:{triggered_trades:7,win_rate:42.8,expectancy:-1.2,profit_factor:.9,net_simulated_pnl:-8.4,maximum_drawdown:52,average_hold_minutes:7,evidence:"INSUFFICIENT"}},normalization:"per triggered contract; realistic P&L primary"},
  "/api/system/status":{status:"ok",market_status:"open",database:"connected",data_freshness:"fresh",worker_status:"healthy",worker_last_success:new Date().toISOString(),provider_status:"not_queried",timestamp:new Date().toISOString()},
  "/api/scanner":scannerPayload,
};

http.createServer((request,response)=>{let body=routes[request.url];if(request.url?.startsWith("/api/trades/history?"))body=journalPayload;if(request.url?.startsWith("/api/trades/OB%3Ajournal-1/management?"))body=journalManagement;response.setHeader("Access-Control-Allow-Origin","http://localhost:3000");response.setHeader("Content-Type","application/json");response.writeHead(body?200:404);response.end(JSON.stringify(body||{detail:"Not found"}))}).listen(8000,()=>console.log("OptionBeacon mock API on http://localhost:8000"));
